name: CEO Installer

on: [push]

jobs:
  ceo-installer:

    runs-on: ubuntu-latest

    steps:
    
    - name: Environment variables & secrets validation
      env: 
        EOS_PRIVATE_KEY: ${{ secrets.EOS_PRIVATE_KEY }}
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
        PINATA_SECRET_API_KEY: ${{ secrets.PINATA_SECRET_API_KEY }}
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      run: |
        if [ -z "$EOS_PRIVATE_KEY" ]; then echo "In order to continue, you must first create a secret named EOS_PRIVATE_KEY" && exit 1; fi 
        if [ -z "$PINATA_API_KEY" ]; then echo "In order to continue, you must first create a secret named PINATA_API_KEY" && exit 1; fi
        if [ -z "$PINATA_SECRET_API_KEY" ]; then echo "In order to continue, you must first create a secret named PINATA_SECRET_API_KEY" && exit 1; fi
        if [ -z "$CLOUDFLARE_API_KEY" ]; then echo "In order to continue, you must first create a secret named CLOUDFLARE_API_KEY" && exit 1; fi  
        if [ -z "$CLOUDFLARE_ZONE_ID" ]; then echo "In order to continue, you must first create a secret named CLOUDFLARE_ZONE_ID" && exit 1 ; fi
    
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Install Node.js 
      uses: actions/setup-node@v1
    
    - name: Deploy CEO Core to EOS mainnet
      run: |
        wget https://github.com/EOSIO/eos/releases/download/v1.8.6/eosio_1.8.6-1-ubuntu-18.04_amd64.deb
        sudo apt install ./eosio_1.8.6-1-ubuntu-18.04_amd64.deb
        cleos version

        echo "deploying..."

    - name: Upload CEO Frontend to IPFS
      run: echo "Uploading the CEO frontend to IPFS network"

    - name: Configure DNS
      run: echo "Configuraing Cloudflare DNS"

