name: OperatorOps Installer

on: [push]

jobs:
  secrets-validation:

    runs-on: ubuntu-latest

    steps:
    
    - name: Deploying smart contracts to EOS...
      env: 
        EOS_PRIVATE_KEY: ${{ secrets.EOS_PRIVATE_KEY }}
      run: |
        [ -z "$EOS_PRIVATE_KEY" ] && echo "You must first create a secret named EOS_PRIVATE_KEY" && exit 1 
        echo "EOS PRV KEY is ${EOS_PRIVATE_KEY}"
    
    - name: Uploading the dWeb application to Pinata...
      env: 
        PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
      run: |
        [ -z "$PINATA_API_KEY" ] && echo "You must first create a secret named PINATA_API_KEY" && exit 1
        echo "PINATA API KEY is ${PINATA_API_KEY}"
      
    - name: Configuring Cloudflare DNS...
      env: 
        CLOUDFLARE_API_KEY: ${{ secrets.CLOUDFLARE_API_KEY }}
      run: |
        [ -z "$CLOUDFLARE_API_KEY" ] && echo "You must first create a secret named CLOUDFLARE_API_KEY" && exit 1  
        echo "CLOUDFLARE API KEY is ${CLOUDFLARE_API_KEY}"      

  frontend-setup:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        env
        cd frontend
        npm install
        node app.js